In [1]:
import sys,os
import tensorflow as tf
sys.path.insert(0, "../../../../../")

2023-08-11 16:36:36.277127: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-11 16:36:36.313417: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-11 16:36:36.314301: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-11 16:36:37.037552: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
# tf.keras.backend.set_floatx('float32')

In [3]:
from nn_models.nn_models.tf.image.hrnet.hrnetv3_seg_hongyi import (
    make_a_keras_model, basic_block, bottleneck_block, stem_net, construct_transition_layer, conv_block,
    fuse_to_single_output, construct_fuse_layers, make_layer_branches, seg_hrnet, final_segmentation_layer, seg_prob_to_category,
    vin_prob_to_string
)
import string

# tmp test

In [4]:
inp1 = tf.keras.layers.Input(shape=(256,1780,20))
seg_cate = seg_prob_to_category(inp1)
inp2 = tf.random.normal(shape=(256,1780,20))
seg_cate2 = seg_prob_to_category(inp2)

2023-08-11 14:20:29.303835: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


# tmp test 2

In [5]:

inp2 = tf.random.uniform(shape=(17, 36), maxval=36)
seg_cate2 = vin_prob_to_string(inp2)

In [6]:
seg_cate2

<tf.Tensor: shape=(), dtype=string, numpy=b'2G1GZUWT0M7OGF4VS'>

# test seg_hrnet

In [4]:
model = seg_hrnet(image_shape=(128, 1024, 3), n_class=20)

2023-08-11 16:36:42.920223: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [5]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 128, 1024, 3)]       0         []                            
                                                                                                  
 conv2d (Conv2D)             (None, 64, 512, 64)          1728      ['input_1[0][0]']             
                                                                                                  
 batch_normalization (Batch  (None, 64, 512, 64)          256       ['conv2d[0][0]']              
 Normalization)                                                                                   
                                                                                                  
 activation (Activation)     (None, 64, 512, 64)          0         ['batch_normalization[0][0

 activation_8 (Activation)   (None, 64, 512, 64)          0         ['batch_normalization_9[0][0]'
                                                                    ]                             
                                                                                                  
 conv2d_10 (Conv2D)          (None, 64, 512, 256)         16384     ['activation_8[0][0]']        
                                                                                                  
 batch_normalization_10 (Ba  (None, 64, 512, 256)         1024      ['conv2d_10[0][0]']           
 tchNormalization)                                                                                
                                                                                                  
 add_2 (Add)                 (None, 64, 512, 256)         0         ['batch_normalization_10[0][0]
                                                                    ',                            
          

 add_8 (Add)                 (None, 32, 256, 64)          0         ['batch_normalization_25[0][0]
                                                                    ',                            
                                                                     'activation_14[0][0]']       
                                                                                                  
 add_4 (Add)                 (None, 64, 512, 32)          0         ['batch_normalization_17[0][0]
                                                                    ',                            
                                                                     'activation_13[0][0]']       
                                                                                                  
 activation_24 (Activation)  (None, 32, 256, 64)          0         ['add_8[0][0]']               
                                                                                                  
 activatio

                                                                                                  
 activation_28 (Activation)  (None, 32, 256, 64)          0         ['add_10[0][0]']              
                                                                                                  
 activation_20 (Activation)  (None, 64, 512, 32)          0         ['add_6[0][0]']               
                                                                                                  
 conv2d_30 (Conv2D)          (None, 32, 256, 64)          36864     ['activation_28[0][0]']       
                                                                                                  
 conv2d_22 (Conv2D)          (None, 64, 512, 32)          9216      ['activation_20[0][0]']       
                                                                                                  
 batch_normalization_30 (Ba  (None, 32, 256, 64)          256       ['conv2d_30[0][0]']           
 tchNormal

 conv2d_38 (Conv2D)          (None, 16, 128, 128)         73728     ['add_13[0][0]']              
                                                                                                  
 conv2d_39 (Conv2D)          (None, 64, 512, 32)          9216      ['activation_31[0][0]']       
                                                                                                  
 conv2d_37 (Conv2D)          (None, 32, 256, 64)          36864     ['add_13[0][0]']              
                                                                                                  
 batch_normalization_38 (Ba  (None, 16, 128, 128)         512       ['conv2d_38[0][0]']           
 tchNormalization)                                                                                
                                                                                                  
 batch_normalization_39 (Ba  (None, 64, 512, 32)          128       ['conv2d_39[0][0]']           
 tchNormal

 conv2d_42 (Conv2D)          (None, 64, 512, 32)          9216      ['activation_36[0][0]']       
                                                                                                  
 conv2d_49 (Conv2D)          (None, 32, 256, 64)          36864     ['activation_43[0][0]']       
                                                                                                  
 batch_normalization_57 (Ba  (None, 16, 128, 128)         512       ['conv2d_57[0][0]']           
 tchNormalization)                                                                                
                                                                                                  
 batch_normalization_42 (Ba  (None, 64, 512, 32)          128       ['conv2d_42[0][0]']           
 tchNormalization)                                                                                
                                                                                                  
 batch_nor

                                                                                                  
 conv2d_52 (Conv2D)          (None, 32, 256, 64)          36864     ['activation_46[0][0]']       
                                                                                                  
 batch_normalization_60 (Ba  (None, 16, 128, 128)         512       ['conv2d_60[0][0]']           
 tchNormalization)                                                                                
                                                                                                  
 conv2d_45 (Conv2D)          (None, 64, 512, 32)          9216      ['activation_39[0][0]']       
                                                                                                  
 batch_normalization_52 (Ba  (None, 32, 256, 64)          256       ['conv2d_52[0][0]']           
 tchNormalization)                                                                                
          

 conv2d_68 (Conv2D)          (None, 16, 128, 64)          8192      ['activation_57[0][0]']       
                                                                                                  
 activation_58 (Activation)  (None, 32, 256, 64)          0         ['batch_normalization_69[0][0]
                                                                    ']                            
                                                                                                  
 conv2d_64 (Conv2D)          (None, 32, 256, 32)          2048      ['activation_49[0][0]']       
                                                                                                  
 conv2d_65 (Conv2D)          (None, 16, 128, 32)          4096      ['activation_57[0][0]']       
                                                                                                  
 conv2d_66 (Conv2D)          (None, 32, 256, 64)          18432     ['activation_41[0][0]']       
          

 batch_normalization_74 (Ba  (None, 32, 256, 64)          256       ['conv2d_74[0][0]']           
 tchNormalization)                                                                                
                                                                                                  
 batch_normalization_75 (Ba  (None, 16, 128, 128)         512       ['conv2d_75[0][0]']           
 tchNormalization)                                                                                
                                                                                                  
 batch_normalization_76 (Ba  (None, 8, 64, 256)           1024      ['conv2d_76[0][0]']           
 tchNormalization)                                                                                
                                                                                                  
 batch_normalization_73 (Ba  (None, 64, 512, 32)          128       ['conv2d_73[0][0]']           
 tchNormal

                                                                                                  
 add_41 (Add)                (None, 8, 64, 256)           0         ['batch_normalization_102[0][0
                                                                    ]',                           
                                                                     'activation_62[0][0]']       
                                                                                                  
 add_29 (Add)                (None, 64, 512, 32)          0         ['batch_normalization_78[0][0]
                                                                    ',                            
                                                                     'activation_59[0][0]']       
                                                                                                  
 activation_72 (Activation)  (None, 32, 256, 64)          0         ['add_33[0][0]']              
          

                                                                     'activation_64[0][0]']       
                                                                                                  
 activation_74 (Activation)  (None, 32, 256, 64)          0         ['add_34[0][0]']              
                                                                                                  
 activation_82 (Activation)  (None, 16, 128, 128)         0         ['add_38[0][0]']              
                                                                                                  
 activation_90 (Activation)  (None, 8, 64, 256)           0         ['add_42[0][0]']              
                                                                                                  
 activation_66 (Activation)  (None, 64, 512, 32)          0         ['add_30[0][0]']              
                                                                                                  
 conv2d_89

                                                                                                  
 activation_68 (Activation)  (None, 64, 512, 32)          0         ['add_31[0][0]']              
                                                                                                  
 conv2d_91 (Conv2D)          (None, 32, 256, 64)          36864     ['activation_76[0][0]']       
                                                                                                  
 conv2d_99 (Conv2D)          (None, 16, 128, 128)         147456    ['activation_84[0][0]']       
                                                                                                  
 conv2d_107 (Conv2D)         (None, 8, 64, 256)           589824    ['activation_92[0][0]']       
                                                                                                  
 conv2d_83 (Conv2D)          (None, 64, 512, 32)          9216      ['activation_68[0][0]']       
          

 conv2d_112 (Conv2D)         (None, 8, 64, 32)            8192      ['activation_94[0][0]']       
                                                                                                  
 conv2d_109 (Conv2D)         (None, 64, 512, 32)          1024      ['activation_70[0][0]']       
                                                                                                  
 batch_normalization_110 (B  (None, 32, 256, 32)          128       ['conv2d_110[0][0]']          
 atchNormalization)                                                                               
                                                                                                  
 batch_normalization_111 (B  (None, 16, 128, 32)          128       ['conv2d_111[0][0]']          
 atchNormalization)                                                                               
                                                                                                  
 batch_nor

# test loss

In [6]:
rand_img = tf.random.normal(shape=(1,128,1024,3))
output = model(rand_img)

In [7]:
output.keys()

dict_keys(['segment_prob', 'vin_prob', 'segment_categoy', 'vin_category'])

In [8]:
output["segment_prob"]

<tf.Tensor: shape=(1, 128, 1024, 20), dtype=float32, numpy=
array([[[[0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         ...,
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.99999994, 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.99999994, 0.        , ..., 0.        ,
          0.        , 0.        ]],

        [[0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         ...,
         [0.        , 0.    

In [9]:
output["vin_prob"]

<tf.Tensor: shape=(1, 17, 36), dtype=float32, numpy=
array([[[0.        , 0.99999994, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.99999994, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.     

In [11]:
loss = tf.keras.losses.SparseCategoricalCrossentropy(
    name='sparse_categorical_crossentropy'
)

In [14]:
fake_label = tf.random.uniform(shape=(1,128, 1024), dtype=tf.int32, maxval= 19)

In [15]:
loss(fake_label, output["segment_prob"])

<tf.Tensor: shape=(), dtype=float32, numpy=15.472366>

In [12]:
loss(tf.random.uniform(shape=(1,17), dtype=tf.int32, maxval= 36), output["vin_prob"])

<tf.Tensor: shape=(), dtype=float32, numpy=15.169975>

In [16]:
output["vin_category"]

<tf.Tensor: shape=(1, 17), dtype=int32, numpy=
array([[ 1, 17,  1,  1,  7,  1, 17,  1,  1, 35, 17,  1,  1,  5, 33,  1,
         1]], dtype=int32)>

In [17]:
output["segment_categoy"]

<tf.Tensor: shape=(1, 128, 1024), dtype=int64, numpy=
array([[[ 5,  5,  5, ...,  6,  1,  1],
        [ 5,  5,  5, ...,  6,  1,  1],
        [ 5,  5,  5, ..., 13,  6,  6],
        ...,
        [ 1,  1,  1, ...,  1,  1,  1],
        [ 1,  1,  1, ...,  1,  1,  1],
        [ 1,  1,  1, ...,  1,  1,  1]]])>

# test

In [55]:
inp = tf.keras.layers.Input(shape=(256, 1800, 22))
x = tf.keras.layers.Conv2D(filters=256, kernel_size=(256,1), padding="valid")(inp)
x1 = tf.keras.layers.Lambda(lambda x: tf.math.reduce_mean(x, axis=2))(inp)
x2 = tf.keras.layers.Permute(dims=(2,1))(x1)

x3 = tf.keras.layers.MultiHeadAttention(5,64)(x2, x2, return_attention_scores=False)
x4 = tf.keras.layers.Dense(36)(x3)
x5 = tf.keras.layers.Softmax()(x4)

In [56]:
model22 = tf.keras.Model(inp, x5)

In [57]:
model22.summary()

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_8 (InputLayer)        [(None, 256, 1800, 22)]      0         []                            
                                                                                                  
 lambda_14 (Lambda)          (None, 256, 22)              0         ['input_8[0][0]']             
                                                                                                  
 permute_7 (Permute)         (None, 22, 256)              0         ['lambda_14[0][0]']           
                                                                                                  
 multi_head_attention_4 (Mu  (None, 22, 256)              328896    ['permute_7[0][0]',           
 ltiHeadAttention)                                                   'permute_7[0][0]']     

In [46]:
x2[]

<KerasTensor: shape=(None, 22, 256) dtype=float32 (created by layer 'permute_3')>